---
title: "Bioheart Distribution Analysis"
author: "Elijah WIllie"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = TRUE) 
knitr::opts_chunk$set(fig.width=10, fig.height=6) 
```

```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(reticulate)
  library(keras)
  library(tidyverse)
  library(FuseSOM)
  library(ggsci)
  library(uwot)
  library(data.table)
  library(SingleCellExperiment)
  library(SKM)
  library(caret)
  library(ROCR)
  library(cvAUC)
  library(spicyR)
  library(cyCombine)
  library(ClassifyR)
  library(cowplot)
  library(psych)
  library(igraph)
  library(tensorflow)
  library(Spectrum)
  library(glmnet)
  library(ipflasso)
  library(prioritylasso)
  library(hopach)
  library(rpart)
  library(rpart.plot)
  # library(ruta)
  library(ggtree)
  library(ape)
  library(grpregOverlap)
  library(ggiraph)
  library(scales)
  library(ggnewscale)
})

k = backend()     # this where the software used to break
source('~/Documents/PhD/bioheart_analysis/scripts/autoClass.R')
source('~/Documents/PhD/bioheart_analysis/scripts/helperFuncs.R')
source('~/Documents/PhD/bioheart_analysis/scripts/customCV.R')
source('~/Documents/PhD/bioheart_analysis/scripts/predClusters.R')
source('~/Documents/PhD/bioheart_analysis/scripts/trainClassifier.R')
source('~/Documents/PhD/bioheart_analysis/scripts/deep_learning_helper_funcs.R')
# source('~/Documents/PhD/DeepLearning_CyTOF/robust_ae.R')
```

# load both studies
```{r}
nCores <- 4
BPPARAM <- simpleSeg:::generateBPParam(nCores)
theme_set(theme_classic())
```

# Set the markers
```{r}
useMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE')

allMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE', "CD11b", "CD253_TRAIL",
                "CD34", "CD61", "CD11c", "eNOS", "LOX_1", "CD86", "CD16", "CD45_106",
                "CD45_108", "P2X7", "NOX5")
```

# Read in the dataset
```{r}
# study 4
set.seed(1994)
df <- fread('../raw_data/bioheart_ct_cytof_data_b4_mg.csv',
              nThread = 7) %>%
  as.data.frame() 

df <- df[which(df$mg_cell_type_distinct != ""), ]
df$sample_id <- as.factor(df$sample_id)
df_trans <- log(abs(df[, useMarkers]) + 1)
df_trans$sample_id <- df$sample_id

preProcValues <- preProcess(df_trans[, useMarkers], method = c("range"))
df_trans_scaled <- predict(preProcValues, df_trans[, useMarkers])
df_trans_scaled$sample_id <- df$sample_id
# df <- df[which(df$mg_cell_type_distinct != "other"), ]
```

```{r}
p.cd4.raw <- df %>%
  ggplot(aes(x = CD4)) + 
  geom_density(aes(color = sample_id)) +
  theme(legend.position = "none") + 
  ggtitle("CD4 before transformation") +
  ylab("Score") +
  theme(
      plot.title = element_text(color="Black", size=18, face="bold", hjust = 0.5),
    )
```

```{r}
p.cd4.trans <- df_trans %>%
  ggplot(aes(x = CD4)) + 
  geom_density(aes(color = sample_id)) +
  theme(legend.position = "none") + 
  ggtitle("CD4 after log() transformation") +
  ylab("Score") +
  theme(
      plot.title = element_text(color="Black", size=18, face="bold", hjust = 0.5),
    )
```

```{r, fig.height=6, fig.width=12}
cowplot::plot_grid(p.cd4.raw, p.cd4.trans)
```

# Now do MinMax
```{r}
p.cd4.trans.scaled <- df_trans_scaled %>%
  ggplot(aes(x = CD4)) + 
  geom_density(aes(color = sample_id)) +
  theme(legend.position = "none") + 
  ggtitle("CD4 after log() and MinMax scaling") +
  ylab("Score") +
  theme(
      plot.title = element_text(color="Black", size=18, face="bold", hjust = 0.5),
    )
```

```{r, fig.height=9, fig.width=12}
cowplot::plot_grid(p.cd4.raw, p.cd4.trans,
                   p.cd4.trans.scaled)
```