---
title: "BioHEART-CT Normalisation cyCombine"
author: "Elijah WIllie"
date: "2024-08-22"
output: html_document
---

```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(tidyverse)
  library(FuseSOM)
  library(ggsci)
  library(uwot)
  library(data.table)
  library(SingleCellExperiment)
  library(caret)
  library(ROCR)
  library(psych)
  library(tensorflow)
  library(glmnet)
  library(data.tree)
  library(ggtree)
  library(ape)
  library(grpregOverlap)
  library(ggiraph)
  library(scales)
  library(ggnewscale)
})
source('~/Documents/PhD/bioheart_analysis/scripts/helperFuncs.R')
source('~/Documents/PhD/bioheart_analysis/scripts/customCV.R')
# set_random_seed(1994)
```

# load both studies
```{r}
nCores <- 4
BPPARAM <- simpleSeg:::generateBPParam(nCores)
theme_set(theme_classic())
```

# Set the markers
```{r}
useMarkers <- c('HLA_DR', 'CD3',  'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE')

allMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE', "CD11b", "CD253_TRAIL",
                "CD34", "CD61", "CD11c", "eNOS", "LOX_1", "CD86", "CD16", "CD45_106",
                "CD45_108", "P2X7", "NOX5")
```

# Load normalised data
```{r}
load('../sce_dat/bioheart_cyCombine_batch_corrected.RData')
# load('../sce_dat/study_3_MG_MMD_VAE_sce.RData')
```

# Look at study 4
```{r}
df_raw <- assay(sce, "counts") %>%
  t() %>%
  as.data.frame() %>%
  dplyr::mutate(sample_id = sce$sample_id) %>%
  # dplyr::mutate(CellType = sce_norm$mg_cell_type_distinct) %>%
  # dplyr::mutate(Gensini = sce$) %>%
  dplyr::mutate(Batch = sce$batch)

df_norm <- assay(sce, "corrected") %>%
  t() %>%
  as.data.frame() %>%
  dplyr::mutate(sample_id = sce$sample_id) %>%
  # dplyr::mutate(CellType = sce_norm$mg_cell_type_distinct) %>%
  # dplyr::mutate(Gensini = sce$gensini_bin) %>%
  dplyr::mutate(Batch = sce$batch)

markers <- c('CD4', 'CD20', 'CD3', 'CD8a')
```

```{r}
p.den.raw <- df_raw %>%
  dplyr::select(c(markers, sample_id, Batch)) %>%
  melt(id.var = c('sample_id', 'Batch')) %>%
  dplyr::mutate(sample_id = as.factor(sample_id)) %>%
  ggplot(aes(x = value, color = sample_id)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ variable, scales = "free") +
  theme_minimal() +
  theme(legend.position = 'none') +
  labs(title = "Density Plots of Raw Marker Intensities", x = "Intensity", y = "Density")
```

```{r}
p.den.norm <- df_norm %>%
  dplyr::select(c(markers, sample_id, Batch)) %>%
  melt(id.var = c('sample_id', 'Batch')) %>%
  dplyr::mutate(sample_id = as.factor(sample_id)) %>%
  ggplot(aes(x = value, color = sample_id)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ variable, scales = "free") +
  theme_minimal() +
  theme(legend.position = 'none') +
  labs(title = "Density Plots of cyCombine Marker Intensities", x = "Intensity", y = "Density")
```

```{r}
p.den.raw <- df_raw %>%
  dplyr::select(c(markers, sample_id, Batch)) %>%
  melt(id.var = c('sample_id', 'Batch')) %>%
  dplyr::mutate(sample_id = as.factor(sample_id)) %>%
  dplyr::mutate(Batch = as.factor(Batch)) %>%
  ggplot(aes(x = value, color = Batch)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ variable, scales = "free") +
  theme_minimal() +
  theme(legend.position = 'none') +
  labs(title = "Density Plots of Raw Marker Intensities", x = "Intensity", y = "Density")
```

```{r}
p.den.norm <- df_norm %>%
  dplyr::select(c(markers, sample_id, Batch)) %>%
  melt(id.var = c('sample_id', 'Batch')) %>%
  dplyr::mutate(sample_id = as.factor(sample_id)) %>%
  dplyr::mutate(Batch = as.factor(Batch)) %>%
  ggplot(aes(x = value, color = Batch)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ variable, scales = "free") +
  theme_minimal() +
  theme(legend.position = 'none') +
  labs(title = "Density Plots of cyCombine Marker Intensities", x = "Intensity", y = "Density")
```

