---
title: "cyCombine all batches marker expression"
author: "Elijah WIllie"
date: "2024-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = TRUE) 
knitr::opts_chunk$set(fig.width=10, fig.height=6) 
```

```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(reticulate)
  library(keras)
  library(tidyverse)
  library(FuseSOM)
  library(ggsci)
  library(uwot)
  library(data.table)
  library(SingleCellExperiment)
  library(SKM)
  library(caret)
  library(ROCR)
  library(cvAUC)
  library(spicyR)
  library(cyCombine)
  library(ClassifyR)
  library(cowplot)
  library(psych)
  library(igraph)
  library(tensorflow)
  library(Spectrum)
  library(glmnet)
  library(ipflasso)
  library(prioritylasso)
  library(hopach)
  library(rpart)
  library(rpart.plot)
  # library(ruta)
  library(ggtree)
  library(ape)
  library(grpregOverlap)
  library(ggiraph)
  library(scales)
  library(ggnewscale)
})

k = backend()     # this where the software used to break
source('~/Documents/PhD/bioheart_analysis/scripts/autoClass.R')
source('~/Documents/PhD/bioheart_analysis/scripts/helperFuncs.R')
source('~/Documents/PhD/bioheart_analysis/scripts/deep_learning_helper_funcs.R')
source('~/Documents/PhD/bioheart_analysis/scripts/customCV.R')
source('~/Documents/PhD/bioheart_analysis/scripts/predClusters.R')
source('~/Documents/PhD/bioheart_analysis/scripts/trainClassifier.R')
# source('~/Documents/PhD/DeepLearning_CyTOF/robust_ae.R')
```

```{r}
useMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE')

allMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE', "CD11b", "CD253_TRAIL",
                "CD34", "CD61", "CD11c", "eNOS", "LOX_1", "CD86", "CD16", "CD45_106",
                "CD45_108", "P2X7", "NOX5")
```

# Read in the datasets
```{r}
set.seed(1994)
df_4 <- fread('../raw_data/bioheart_ct_cytof_data_b4_mg.csv',
              nThread = 7) %>%
  as.data.frame() %>%
  dplyr::select(c(useMarkers, "sample_id", "CyTOF.Batch", "Gender", "gensini_bin"))

# df_4 <- df_4[which(df_4$mg_cell_type_distinct != ""), ]

colnames(df_4)[colnames(df_4) == "CyTOF.Batch"] = "batch_old"

```

```{r}
df_3 <- fread('../raw_data/study_3_sub.csv',
              nThread = 7) %>% 
  as.data.frame() %>%
  dplyr::select(c(useMarkers, "sample_id", "CyTOF.Batch", "Gender", "Gensini"))
df_3$gensini_bin <- factor(if_else(df_3$Gensini > 0, 1, 0))

colnames(df_3)[colnames(df_3) == "CyTOF.Batch"] = "batch_old"
```

## Combine study 4 and study 3
```{r}
common_cols <- intersect(colnames(df_4), colnames(df_3))
df <- rbind(df_4[, common_cols], df_3[, common_cols]) 
# update study information
df$batch <- if_else(df$batch_old %like% 4, 4, 3)
```

```{r}
df[, useMarkers] <- cyCombine::transform_asinh(df, markers = useMarkers)
```

# Do batch correction
```{r}
df_norm <- df %>%
  batch_correct(markers = useMarkers,
                seed = 1994,
                norm_method = "scale", # "rank" is recommended when combining data with heavy batch effects
                rlen = 10 # Consider a larger value, if results are not convincing (e.g. 100)
                )
```

```{r}
df_4_norm <- df_norm[df_norm$batch == '4', ]
df_3_norm <- df_norm[df_norm$batch == '3', ]
```

```{r}
stat_test_study_4 <- df_4_norm %>%
  dplyr::select(c(useMarkers, "sample_id", "Gender", "gensini_bin")) %>%
  dplyr::group_by(sample_id, Gender, gensini_bin) %>%
  summarise_at(useMarkers, mean) %>%
  pivot_longer(-c(Gender, sample_id, gensini_bin), names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  t_test(value ~ Gender) %>%
  adjust_pvalue(method = "BH") %>%
  add_significance()
stat_test_study_4
```

```{r}
stat_test_study_3 <- df_3_norm %>%
  dplyr::select(c(useMarkers, "sample_id", "Gender", "gensini_bin")) %>%
  dplyr::group_by(sample_id, Gender, gensini_bin) %>%
  summarise_at(useMarkers, mean) %>%
  pivot_longer(-c(Gender, sample_id, gensini_bin), names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  t_test(value ~ Gender) %>%
  adjust_pvalue(method = "BH") %>%
  add_significance()
stat_test_study_3
```

```{r}
data.frame(Study_4 = stat_test_study_4$statistic,
                      Study_3 = stat_test_study_3$statistic) %>%
  ggscatter(x = "Study_4", y = "Study_3", title = "cyCombine",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   ) + 
  stat_cor(aes(label = ..r.label..), label.x = 3)
```