---
title: "Bioheart pairwise batches unnormalised"
author: "Elijah WIllie"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = TRUE) 
knitr::opts_chunk$set(fig.width=10, fig.height=6) 
```

```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(reticulate)
  library(keras)
  library(tidyverse)
  library(FuseSOM)
  library(ggsci)
  library(uwot)
  library(data.table)
  library(SingleCellExperiment)
  library(SKM)
  library(caret)
  library(ROCR)
  library(cvAUC)
  library(spicyR)
  library(cyCombine)
  library(ClassifyR)
  library(cowplot)
  library(psych)
  library(igraph)
  library(tensorflow)
  library(Spectrum)
  library(glmnet)
  library(ipflasso)
  library(prioritylasso)
  library(hopach)
  library(rpart)
  library(rpart.plot)
  # library(ruta)
  library(ggtree)
  library(ape)
  library(grpregOverlap)
  library(ggiraph)
  library(scales)
  library(ggnewscale)
})

k = backend()     # this where the software used to break
source('~/Documents/PhD/bioheart_analysis/scripts/autoClass.R')
source('~/Documents/PhD/bioheart_analysis/scripts/helperFuncs.R')
source('~/Documents/PhD/bioheart_analysis/scripts/customCV.R')
source('~/Documents/PhD/bioheart_analysis/scripts/predClusters.R')
source('~/Documents/PhD/bioheart_analysis/scripts/trainClassifier.R')
source('~/Documents/PhD/bioheart_analysis/scripts/deep_learning_helper_funcs.R')
# source('~/Documents/PhD/DeepLearning_CyTOF/robust_ae.R')
```

# load both studies
```{r}
nCores <- 4
BPPARAM <- simpleSeg:::generateBPParam(nCores)
theme_set(theme_classic())
```

# Set the markers
```{r}
useMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE')

allMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE', "CD11b", "CD253_TRAIL",
                "CD34", "CD61", "CD11c", "eNOS", "LOX_1", "CD86", "CD16", "CD45_106",
                "CD45_108", "P2X7", "NOX5")
```

# Read in the dataset
```{r}
# study 4
set.seed(1994)
df <- fread('../raw_data/bioheart_ct_cytof_data_b4_mg.csv',
              nThread = 7) %>%
  as.data.frame() 

df <- df[which(df$mg_cell_type_distinct != ""), ]
# df[, useMarkers] <- log(abs(df[, useMarkers]) + 1)
# df <- df[which(df$mg_cell_type_distinct != "other"), ]
```

```{r}
# Define a list of items
batches <- unique(df$CyTOF.Batch)

# Generate all pairwise combinations
pairwise_combinations <- combn(batches, 2)

# Print the result
pairwise_combinations_df <- as.data.frame(t(pairwise_combinations))
colnames(pairwise_combinations_df) <- c('Train', 'Test')
```

```{r}
stab_samps <- c()
ari_mg <- c()
nmi_mg <- c()
ari_fs <- c()
nmi_fs <- c()

for(i in 1:nrow(pairwise_combinations_df)){
  
  cur_row <- pairwise_combinations_df[i, ]
  train_batch <- df[df$CyTOF.Batch == cur_row[[1]], ]
  test_batch <- df[df$CyTOF.Batch == cur_row[[2]], ]
  
  message(paste0("Training on batch: ", cur_row[[1]]))
  message(paste0("Testing on batch: ", cur_row[[2]]))
  
  preProcValues <- preProcess(train_batch[, useMarkers], method = c("range"))
  train_batch[, useMarkers] <- predict(preProcValues, train_batch[, useMarkers])
  test_batch[, useMarkers] <- predict(preProcValues, test_batch[, useMarkers])
  
  message("Now fitting deep learning normalisation model\n")
  # compute most stable sample
  
  message("Now creating SCE object for training batches\n")
  # cluster training data using FuseSOM
  sce_train_batch <- SingleCellExperiment(assays = list(norm = t(train_batch[, useMarkers])
  ),
  colData = train_batch %>% dplyr::select(-useMarkers))
  
  message("Now training cell type prediction model\n")
  train_batch$clusters_mg <- factor(sce_train_batch$mg_cell_type_distinct)
  train_batch$sample_id <- sce_train_batch$sample_id
  train_batch$batch <- sce_train_batch$CyTOF.Batch
  
  # subset the normalised training batch data to 1000 cells from each population
  # Manually gated
  train_batch_sub_mg <- train_batch %>%
  group_by(clusters_mg) %>%
  slice_sample(n = 1000)
  
  # training MG model
  nnet_model_mg <- fitCelltypeModel(train_x = train_batch_sub_mg[, useMarkers],
                                  train_y = train_batch_sub_mg$clusters_mg)
  
  message("Now predicting cell types\n")
  # MG
  batch_clusters_mg <- nnet_model_mg %>%
    predict(as.matrix(test_batch[, useMarkers]))
  pred_clusters_mg <- batch_clusters_mg$predicted
  
  message("Now computing concordance for MG clusters\n")
  # compute concordance for MG
  concor_mg <- computeConcordance(test_batch$mg_cell_type_distinct, pred_clusters_mg)
  ari_mg <- c(ari_mg, concor_mg$ARI)
  nmi_mg <- c(nmi_mg, concor_mg$NMI)
}
```


# Collate the final data
```{r}
dat_final_mg <- data.frame(ARI = ari_mg, 
                           NMI = nmi_mg, 
                           Cluster = rep('MG', nrow(pairwise_combinations_df)))
dat_final_mg <- cbind(pairwise_combinations_df, dat_final_mg)

write.csv(dat_final_mg, '../concordance_data/deep_learning_pairwise_batches_unnorm_min_max.csv', row.names = F)
```