---
title: "Study 4 scMerge Analysis"
author: "Elijah WIllie"
date: "2024-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = TRUE) 
knitr::opts_chunk$set(fig.width=10, fig.height=6) 
```

```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(reticulate)
  library(keras)
  library(tidyverse)
  library(FuseSOM)
  library(ggsci)
  library(uwot)
  library(data.table)
  library(SingleCellExperiment)
  library(SKM)
  library(caret)
  library(ROCR)
  library(cvAUC)
  library(spicyR)
  library(cyCombine)
  library(ClassifyR)
  library(cowplot)
  library(psych)
  library(igraph)
  library(tensorflow)
  library(Spectrum)
  library(glmnet)
  library(ipflasso)
  library(prioritylasso)
  library(hopach)
  library(rpart)
  library(rpart.plot)
  # library(ruta)
  library(ggtree)
  library(ape)
  library(grpregOverlap)
  library(ggiraph)
  library(scMerge)
})

k = backend()     # this where the software used to break
source('~/Documents/PhD/bioheart_analysis/scripts/autoClass.R')
source('~/Documents/PhD/bioheart_analysis/scripts/helperFuncs.R')
source('~/Documents/PhD/bioheart_analysis/scripts/customCV.R')
source('~/Documents/PhD/bioheart_analysis/scripts/predClusters.R')
source('~/Documents/PhD/bioheart_analysis/scripts/trainClassifier.R')
source('~/Documents/PhD/bioheart_analysis/scripts/deep_learning_helper_funcs.R')
# source('~/Documents/PhD/DeepLearning_CyTOF/robust_ae.R')
```

```{r}
nCores <- 4
BPPARAM <- simpleSeg:::generateBPParam(nCores)
theme_set(theme_classic())
```

```{r}
useMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE')

allMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE', "CD11b", "CD253_TRAIL",
                "CD34", "CD61", "CD11c", "eNOS", "LOX_1", "CD86", "CD16", "CD45_106",
                "CD45_108", "P2X7", "NOX5")
```

# Read in the datasets
```{r}
set.seed(1994)
df <- fread('../raw_data/bioheart_ct_cytof_data_b4_mg.csv',
              nThread = 7) %>%
  as.data.frame()
# %>%
# 
#   group_by(sample_id) %>%
#   slice_sample(n = 5000)

df <- df[which(df$mg_cell_type_distinct != ""), ]
```


```{r}
rowsum_df <- DelayedMatrixStats::rowSums2(df[, useMarkers] %>% as.matrix())
df <- df[rowsum_df != 0, ]
```

```{r}
df[, useMarkers] <- cyCombine::transform_asinh(df[, useMarkers], 
                                                 markers = useMarkers)

```

# Look at study 4
## scMerge
```{r}
sce <- SingleCellExperiment(assays = list(counts = t(df[, useMarkers])
),
colData = df %>% dplyr::select(-useMarkers))
```

```{r}
clinicaldata <- colData(sce) %>%
  as.data.frame() %>%
  dplyr::select(sample_id, gensini_bin, Gender, Age) %>%
  distinct()
# clinicaldata$Gensini_bin <- factor(if_else(clinicaldata$Gensini > 0, 1, 0))

# clinicaldata$gensini_bin <- factor(clinicaldata$gensini_bin)
```


```{r}
exprsMat <- counts(sce)
colnames(exprsMat) <- rownames(df)
scMerge2_res <- scMerge2(exprsMat = exprsMat,
                         batch = sce$CyTOF.Batch,
                         ctl = useMarkers,
                         verbose = TRUE, 
                         ruvK = 5,
                         seed = 1994)
```

```{r}
colnames(scMerge2_res$newY) <- NULL
assay(sce, "scMerge2", withDimnames=FALSE) <- scMerge2_res$newY
df_norm <- scMerge2_res$newY %>%
  t() %>%
  as.data.frame()
```


```{r, eval=F}
set.seed(1994)
sample_pts <- sample(ncol(sce), 100000)
sce_sub <- sce[, sample_pts]

sce_sub <- scater::runUMAP(sce_sub,
                         subset_row = useMarkers,
                         exprs_values = "counts",
                         BPPARAM = BPPARAM, 
                         n_threads = 7,
                         metric = 'cosine',
                         verbose = T)

df_raw_umap <- reducedDim(sce_sub, 'UMAP') %>%
    as.data.frame()
colnames(df_raw_umap) <- c('UMAP 1', 'UMAP 2')

df_raw_umap$Batch <- sce_sub$CyTOF.Batch

# df_raw_umap$Study <- if_else(df_raw_umap$Batch %like% '3', '3', '4')
```

```{r, eval=FALSE}
set.seed(1994)
sce_sub <- scater::runUMAP(sce_sub,
                         subset_row = useMarkers,
                         exprs_values = "scMerge2",
                         BPPARAM = BPPARAM, 
                         n_threads = 7,
                         metric = 'cosine',
                         verbose = T)

df_scmerge2_umap <- reducedDim(sce_sub, 'UMAP') %>%
    as.data.frame()
colnames(df_scmerge2_umap) <- c('UMAP 1', 'UMAP 2')

df_scmerge2_umap$Batch <- sce_sub$CyTOF.Batch
```

```{r, eval=FALSE}
p.raw.umap <- df_raw_umap %>% ggplot(aes(`UMAP 1`, `UMAP 2`)) +
    geom_point(aes(color = `Batch`), size = 1) + 
    ggtitle('Raw data - Study 4') +
  # facet_grid(~Study) +
  theme_bw() + 
    theme(axis.text.x = element_text(size = 12),
        plot.title = element_text(size = 15, hjust = 0.5),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12)
        ) + scale_color_d3(palette = 'category20')
```

```{r, eval=FALSE}
p.scmerge2.umap <- df_scmerge2_umap %>% ggplot(aes(`UMAP 1`, `UMAP 2`)) +
    geom_point(aes(color = `Batch`), size = 1) + 
    ggtitle('scMerge2 corrected data - Study 4') +
  theme_bw() +
    theme(axis.text.x = element_text(size = 12),
        plot.title = element_text(size = 15, hjust = 0.5),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12)
        ) + scale_color_d3(palette = 'category20')
```


```{r, eval=FALSE}
pdf(file = "../Plots/scMerge2_UMAP_plots.pdf",   # The directory you want to save the file in
    width = 8, # The width of the plot in inches
    height = 4) # The height of the plot in inches
cowplot::plot_grid(p.raw.umap, p.scmerge2.umap)

dev.off()
```

### Use FuseSOM to cluster the normalised data
```{r}
# run FuseSOM clustering
nclust = 12
sce$clusters_scMerge2 <- NULL
sce <- runFuseSOM(sce, numClusters = nclust, assay = 'scMerge2',
                       verbose = FALSE, clusterCol = "clusters_scMerge2")
```

## Look at heatmap
```{r}
scater::plotGroupedHeatmap(sce, 
                           features = useMarkers, 
                           group = "clusters_scMerge2", 
                           block = "clusters_scMerge2",
                           exprs_values = "scMerge2",
                           center = TRUE, 
                           scale = TRUE, 
                           zlim = c(-3,3),
                           cluster_rows = FALSE)
```

## Look at concordance
```{r}
computeConcordance(sce$clusters_scMerge2, sce$mg_cell_type_distinct)
```


```{r, eval=FALSE}
df_con <- data.frame(ARI = ARI, NMI = NMI, Method = 'scMerge2')
write.csv(df_con, '../concordance_data/scMerge2_concordance_30_clusters.csv', 
          row.names = F)
```

## Perform classification using the scMerge2 clusters
```{r, eval=FALSE}
data <- getProp(sce,
                feature = "clusters_scMerge2", imageID = "sample_id", logit = F)

dat_prop <- data
data <- 2*asin(sqrt(data))

clinicaldata <- colData(sce) %>%
  as.data.frame() %>%
  dplyr::select(sample_id, Gensini, Gender, Age) %>%
  distinct()
clinicaldata$Gensini_bin <- factor(if_else(clinicaldata$Gensini > 0, 1, 0))

encoded_gender <- model.matrix(~Gender-1, data=clinicaldata)
clinicaldata <- cbind(clinicaldata, encoded_gender)

row_names <- rownames(data)

Age <- clinicaldata[match(row_names,clinicaldata$sample_id),
                                      "Age"]
GenderM <- clinicaldata[match(row_names,clinicaldata$sample_id),
                                      c("GenderM")]

clinicaldata_info <- cbind(Age, GenderM)

condition <- factor(clinicaldata[match(row_names,clinicaldata$sample_id),
                                      "Gensini_bin"])


data_logit <- getProp(sce,
                feature = "clusters_scMerge2", imageID = "sample_id", logit = T)
colnames(data_logit) <- paste0(colnames(data_logit), "_logit")
colnames(data) <- paste0(colnames(data), "_prop")
colnames(dat_prop) <- colnames(data)
```

```{r, eval=FALSE}
t <- df_norm
t$sample_id <- df$sample_id

data_mean <- t %>% 
  dplyr::group_by(sample_id) %>%
  dplyr::summarise_at(vars(useMarkers), mean) %>%
  dplyr::select(-sample_id) %>%
  as.data.frame()

data_median <- t %>% 
  group_by(sample_id) %>%
  summarise_at(vars(useMarkers), median) %>%
  dplyr::select(-sample_id) %>%
  as.data.frame()

rownames(data_mean) <- clinicaldata$sample_id
rownames(data_median) <- clinicaldata$sample_id
colnames(data_mean) <- paste0(colnames(data_mean), "_mean")
colnames(data_median) <- paste0(colnames(data_median), "_median")
```


```{r, eval=FALSE}
res.cv <- KFoldCustomEnsemble(dat_prop = data, dat_logit = data_logit, 
                              dat_mean = data_mean,
                              train_y = condition, 
                              nRepeats = 10, k = 10, alpha = 0.2)
```

```{r, eval=FALSE}
aucs <- data.frame(scMerge2 = res.cv$cv_res)
write.csv(aucs, file = '../auc_data/scMerge2_study_4_auc.csv', row.names = F)
```

```{r, fig.height=6, fig.width=9, eval=FALSE}
# pdf(file = "Plots/SVM_CV_plot.pdf",   # The directory you want to save the file in
#     width = 8, # The width of the plot in inches
#     height = 6) # The height of the plot in inches

cv_plot_dat <- res.cv$cv_dat
out <- cvAUC(cv_plot_dat$predictions, cv_plot_dat$labels)

plot(out$perf, col = "black", lty = 3, size = 2,
     main = paste0("10-fold CV with 10 repeats.. Average AUC = ",
                                                      round(out$cvAUC, 2)))
plot(out$perf, col ="red", avg = "threshold", add = TRUE) 

# dev.off()
```

# Look at batch correction performance
```{r, eval=FALSE}
labels <- df_norm %>%
          cyCombine::create_som(rlen = 10,
                                xdim = 8,
                                ydim = 8,
                                markers = useMarkers)

# Add labels
df_norm <- df_norm %>%
  dplyr::mutate(som = labels)
df_norm$id <- 1:nrow(df_norm)
df_norm$batch <- df$CyTOF.Batch


# Transfer labels to uncorrected data
df$id <- 1:nrow(df_norm)
df <- df_norm %>%
  dplyr::select('id', all_of('som')) %>%
  dplyr::left_join(df, by = "id")

df_norm$batch <- df$CyTOF.Batch
df$batch <- df$CyTOF.Batch
```

## Look at Median Absolute Deviation (MAD) score
```{r, eval=F}
mad_val <- df %>%
      cyCombine::evaluate_mad(df_norm,
                              filter_limit = NULL,
                              markers = useMarkers,
                              cell_col = 'som')

mad_dat <- mad_val$mad
```

## Generate density plot for batch correction
```{r, eval=FALSE}
pdf(file = "../Plots/scMerge2_MAD_plot.pdf",   # The directory you want to save the file in
    width = 6, # The width of the plot in inches
    height = 4) # The height of the plot in inches

mad_dat %>%
  ggplot(aes(x = Difference)) + 
  geom_histogram(bins = 30) +
  ggtitle('Histogram of MAD scores for scMerge2', 
          subtitle = paste('Median score:', mad_val$score)) +
  theme_bw() + 
    theme(axis.text.x = element_text(size = 12),
        plot.title = element_text(size = 15, hjust = 0.5,
                                  face = 'bold'),
        plot.subtitle = element_text(size = 15, 
                                     hjust = 0.5, colour = 'blue'),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12)
        )

dev.off()
```

```{r, eval=FALSE}
nclust <- length(unique(sce$clusters_scMerge2))
overlapModel <- runOverlapLasso(data, data_logit, data_mean, nclust = nclust, 
                                alpha = 0.2)
fit <- overlapModel$fit
scaleVals <- overlapModel$scaling
```

```{r, eval=FALSE}
res_mp <- MP_gLasso(fit = fit, group = fit$grp.vec, lambda.type = "min", sort.type = "max")
girafe(code = print(res_mp$plot), width_svg = 8, height_svg = 8)
```

```{r, eval=FALSE}
coefs <- coef(fit) %>%
  as.matrix() %>%
  as.data.frame()
coefs$feature <- rownames(coefs)
# coefs <- coefs[coefs$V1 != 0, ]
```

```{r, fig.height=6, fig.width=12, eval=FALSE}
p <- plotOverlapTree(hc = overlapModel$hc_prop, coefs = coefs,
                     data = res_mp$data, heatmap = F)
p
```


# Save SCE object
```{r, eval=T}
save(sce, file = "../sce_dat/study_4_scMerge_sce.RData")
```

