---
title: "Number of clusters experiment - CMV"
author: "Elijah Willie"
date: "2024-10-10"
output: html_document
---


```{r config, include=FALSE}
# Default points at the unzipped Zenodo archive under $BIOHEART_ROOT/data/.
# Override DEEPLEARNING_CYTOF_ROOT to use a custom location.
external_data_root <- Sys.getenv("DEEPLEARNING_CYTOF_ROOT",
                                 unset = file.path(
                                   Sys.getenv("BIOHEART_ROOT",
                                              unset = "~/Documents/Academic/PhD/bioheart_analysis"),
                                   "data", "dioscRi_analysis_data"))
sce_subdir <- file.path(external_data_root, "sce_objects", "CMV_Study_SDY519")
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
gc()
library(dioscRi)
library(ggplot2)
library(FuseSOM)
library(SingleCellExperiment)
library(tidyverse)
library(data.table)
library(data.tree)
library(tensorflow)
library(keras3)
library(ROCR)
library(psych)
library(pROC)
tensorflow::set_random_seed(1994)
```

```{r}
split_and_extract <- function(string, n) {
  split_strings <- strsplit(string, "\\.")[[1]][[2]]  # Split strings by comma
  return(split_strings)
}
```


```{r}
metaData <- read.csv(file.path(sce_subdir, 'cmv_metadata.csv'))
metaData <- metaData[, -1]

metaData$sample_id <- lapply(metaData$name, split_and_extract)
metaData$sample_id <- unlist(metaData$sample_id)

useMarkers <- c("TCRGD", "IGD","HLADR", "CD94","CD85J","CD8","CD56",
                "CD45RA","CD4","CD38", "CD33", "CD3","CD28","CD27",
                "CD25","CD24","CD20","CD19","CD161","CD16","CD14","CD127","CCR7")
```

```{r}
load(file.path(sce_subdir, "cmv_train_MMD_VAE_sce.RData"))
load(file.path(sce_subdir, "cmv_test_MMD_VAE_sce.RData"))
```

# Set up clinical data
## Training
```{r}
clinicaldata_train <- colData(sce_train) %>%
  as.data.frame() %>%
  dplyr::select(sample_id, CMV_Ab) %>%
  distinct()
clinicaldata_train$condition <- factor(if_else(clinicaldata_train$CMV_Ab == "True", 1, 0))
```

## Testing
```{r}
clinicaldata_test <- colData(sce_test) %>%
  as.data.frame() %>%
  dplyr::select(sample_id, CMV_Ab) %>%
  distinct()
clinicaldata_test$condition <- factor(if_else(clinicaldata_test$CMV_Ab == "True", 1, 0))
```

# Create functions to run the prediction models
```{r}
runPredictionModel <- function(sce_train, sce_test, numClusters,
                               clinical_data_train, clinical_data_test){
  # cluster data into k clusters
  sce_train <- runFuseSOM(sce_train, numClusters = numClusters, assay = 'norm',
                       verbose = FALSE, clusterCol = 'clusters')
  
  # get training and testing data
  train_x <- reducedDim(sce_train, type = "VAE") %>%
  mutate(cellTypes = as.factor(sce_train$clusters))
  test_x <- reducedDim(sce_test, type = "VAE")
  
  # fit cell type classifier
  test_cluster <- trainCellTypeClassifier(trainX = train_x, testX = test_x, model = 'lda')
  sce_test$clusters <- as.factor(test_cluster)
  
  # Compute training features
  data_logit_train <- computeFeatures(sce = sce_train, featureType = 'prop', 
                              cellTypeCol = 'clusters', sampleCol = 'sample_id', 
                              logit = T, useMarkers = useMarkers)
  row_names_train <- rownames(data_logit_train)
  condition_train <- factor(clinical_data_train[match(row_names_train,clinical_data_train$sample_id),
                                      "condition"])
  colnames(data_logit_train) <- as.factor(colnames(data_logit_train))
  markerMeanCellType_train <- computeFeatures(sce = sce_train, featureType = 'mean', 
                              cellTypeCol = 'clusters', sampleCol = 'sample_id', 
                              logit = T, useMarkers = useMarkers)
  colnames(markerMeanCellType_train) <- as.factor(colnames(markerMeanCellType_train))
  
  # compute testing features
   data_logit_test <- computeFeatures(sce = sce_test, featureType = 'prop', 
                              cellTypeCol = 'clusters', sampleCol = 'sample_id', 
                              logit = T, useMarkers = useMarkers)
  row_names_test <- rownames(data_logit_test)
  condition_test <- factor(clinical_data_test[match(row_names_test,clinical_data_test$sample_id),
                                      "condition"])
  colnames(data_logit_test) <- as.factor(colnames(data_logit_test))
  markerMeanCellType_test <- computeFeatures(sce = sce_test, featureType = 'mean', 
                              cellTypeCol = 'clusters', sampleCol = 'sample_id', 
                              logit = T, useMarkers = useMarkers)
  colnames(markerMeanCellType_test) <- as.factor(colnames(markerMeanCellType_test))
  
  
  # generate tree
  trees <- generateTree(features = data_logit_train, method = "ward")
  tree <- trees$tree
  order <- trees$order
  groups <- generateGroups(tree = tree, nClust = numClusters, 
                         proportions = data_logit_train, means = markerMeanCellType_train)
  
  # Combine the feature matrices
  X_train <- cbind(data_logit_train, markerMeanCellType_train) 
    
  # Scale the combined data
  scaleVals <- preProcess(X_train, method = c('scale'))
  X_train <- predict(scaleVals, X_train) %>%
      as.matrix()
    
   # Extract response variable
  y_train <- as.numeric(levels(condition_train))[condition_train]
  # combine feature matrices for the test data
  X_test <- cbind(data_logit_test, markerMeanCellType_test) %>%
  as.matrix()
  X_test <- predict(scaleVals, X_test)
  y_test <- as.numeric(levels(condition_test))[condition_test]
  
  # Fit the overlap group lasso model
  groups <- lapply(groups, sort)
  fit <- fitModel(xTrain = X_train, yTrain = y_train, modelSummary = F,
                groups = groups, penalty = "grLasso", seed = 1994)
  
  test_auc <- plotAUC(fit = fit$fit, xTest = X_test, 
                      yTest = y_test, title = "")
  return(test_auc)
}
```

```{r}
clusters <- seq(6,7)
AUCs <- c()

for(i in 1:length(clusters)){
  numClusters <- clusters[i]
  res <- runPredictionModel(sce_train = sce_train, sce_test = sce_test, numClusters = numClusters, 
                          clinical_data_train = clinicaldata_train, clinical_data_test = clinicaldata_test)
  
  res$plot
  AUCs[i] <- auc(res$preds$Truth, res$preds$Predicted) %>% round(2)
}

```

# Generate line plot of results
```{r}
res_df <- data.frame(Cluster = clusters,
                     AUC = AUCs, Dataset = rep("CMV Study SDY519", 11))
```

