---
title: "cyCombine all batches"
author: "Elijah WIllie"
date: "2024-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = TRUE) 
knitr::opts_chunk$set(fig.width=10, fig.height=6) 
```

```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(tidyverse)
  library(FuseSOM)
  library(ggsci)
  library(uwot)
  library(data.table)
  library(SingleCellExperiment)
  library(caret)
  library(ROCR)
  library(cvAUC)
  library(cyCombine)
  library(iMUBAC)
})
```

```{r}
useMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE')
```

# Read in the datasets
```{r}
set.seed(1994)
bioheart_root <- Sys.getenv("BIOHEART_ROOT",
                            unset = "~/Documents/Academic/PhD/bioheart_analysis")
disc_csv <- {
  cands <- c(
    file.path(bioheart_root, "data/dioscRi_analysis_data/raw_files",
              "bioheart_ct_cytof_data_b4_mg.csv"),
    file.path(bioheart_root, "data/raw_data/bioheart_ct_cytof_data_b4_mg.csv"))
  cands[file.exists(cands)][1]
}
df_4 <- fread(disc_csv, nThread = 7) %>%
  as.data.frame() %>%
    dplyr::select(c(useMarkers, "sample_id", "CyTOF.Batch", "gensini_bin",
                  "mg_cell_type_distinct", "Age", "Statin", "Gender"))

colnames(df_4)[colnames(df_4) == "CyTOF.Batch"] = "batch_old"
colnames(df_4)[colnames(df_4) == "mg_cell_type_distinct"] = "CellType"
colnames(df_4)[colnames(df_4) == "gensini_bin"] = "Gensini_bin"
```

```{r}
set.seed(1994)
val_csv <- {
  cands <- c(
    file.path(bioheart_root, "data/dioscRi_analysis_data/raw_files",
              "all_batches_processed_mg_10K.csv"),
    file.path(bioheart_root, "misc/Study_3_2019/all_batches_processed_mg_10K.csv"),
    file.path(bioheart_root, "Study_3_2019/all_batches_processed_mg_10K.csv"))
  cands[file.exists(cands)][1]
}
df_3 <- fread(val_csv, nThread = 7) %>%
  as.data.frame() %>%
  dplyr::select(c(useMarkers,  "sample_id", "CellTypes", "Batch",
                  "Age", "Statin", "Gender", "Gensini_bin"))

colnames(df_3)[colnames(df_3) == "Batch"] = "batch_old"
colnames(df_3)[colnames(df_3) == "CellTypes"] = "CellType"
```

```{r}
df <- rbind(df_4, df_3)
df$batch <- if_else(df$batch %like% "3", "3", "4")
```

```{r}
df[, useMarkers] <- cyCombine::transform_asinh(df, markers = useMarkers, derand = F)
```

```{r}
colnames(df)[colnames(df) %in% useMarkers] <- gsub("_", "-", colnames(df)[colnames(df) %in% useMarkers])
useMarkers <- gsub("_", "-", useMarkers)
```

# Do batch correction
```{r}
df_norm <- df %>%
  batch_correct(markers = useMarkers,
                seed = 1994,
                norm_method = "scale", # "rank" is recommended when combining data with heavy batch effects
                rlen = 10 # Consider a larger value, if results are not convincing (e.g. 100)
                )
```

# Create single cell experiment object
```{r}
sce_cycombine <- SingleCellExperiment(assays = list(counts = t((df[, useMarkers])),
                                          corrected = t(df_norm[, useMarkers])
),
colData = df %>% dplyr::select(-useMarkers))
```

# Save sce_cycombine object
```{r, eval=T}
out_dir <- file.path(bioheart_root, "data", "dioscRi_analysis_data",
                     "sce_objects", "BioHEART")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
save(sce_cycombine,
     file = file.path(out_dir, "bioheart_cyCombine_batch_corrected.RData"))
```