---
  title: "bioheart Deep Learning"
author: "Elijah WIllie"
date: "2024-03-15"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = TRUE) 
knitr::opts_chunk$set(fig.width=10, fig.height=6) 
```

```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(keras3)
  # library(reticulate)
  # use_virtualenv('r-keras', required = TRUE)
  library(tensorflow)
  library(tidyverse)
  library(FuseSOM)
  library(ggsci)
  library(uwot)
  library(data.table)
  library(SingleCellExperiment)
  library(caret)
  library(ROCR)
  library(psych)
  library(tensorflow)
  library(glmnet)
  library(data.tree)
  library(ggtree)
  library(ape)
  library(grpreg)
  library(ggiraph)
  library(scales)
  library(ggnewscale)
  library(rstatix)
  library(ggpubr)
  library(treekoR)
})
files.sources = list.files(path = '../../dioscRi/R/', full.names = T)
sapply(files.sources, source)
set_random_seed(1994)
```

```{r}
useMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE')

allMarkers <- c('HLA_DR', 'CD3', 'CD4', 'CD8a', 'CD25', 'CD127', 'FoxP3', 'CD27',
                'KLRG1', 'CD56', 'CD45RO', 'CD45RA', 'CD192_CCR2', 'CD194_CCR4',
                'CD196_CCR6',
                'CD39', 'CD38', 'Ki67', 'CD183_CXCR3', 'CCR7', 'CD19', 'CD20',
                'IgD', 'CD14', 'CD304', 'CD141', 'CD1c_PE', "CD11b", "CD253_TRAIL",
                "CD34", "CD61", "CD11c", "eNOS", "LOX_1", "CD86", "CD16", "CD45_106",
                "CD45_108", "P2X7", "NOX5")


final_celltypes <- c(
   "B cells",
   "CD8hi",
   "14+ monos",
   "CD4+ Tconv",
   "CD8lo",
   "NK",
   "16+ monos",
   "CD4+ Treg",
   "pDCs",
   "CD141+ DCs",
   "CD1c+ DCs"
    )


final_celltypes_clustering <- c(
   "B cells",
   "CD8hi",
   "14+ monos",
   "CD4+ Tconv",
   "CD8lo",
   "NK",
   "16+ monos",
   "CD4+ Treg",
   "pDCs",
   "CD141+ DCs",
   "other",
   "CD1c+ DCs",
   ""
    )
```

# Read in the datasets
```{r}
set.seed(1994)
df_4 <- fread('../raw_data/bioheart_ct_cytof_data_b4_mg.csv',
              nThread = 7) %>%
  as.data.frame() %>%
    dplyr::select(c(useMarkers, "sample_id", "CyTOF.Batch", "gensini_bin",
                  "mg_cell_type_distinct", "Age", "Statin", "Gender"))

# df_4 <- df_4[which(df_4$mg_cell_type_distinct != ""), ]

colnames(df_4)[colnames(df_4) == "CyTOF.Batch"] = "Batch"
colnames(df_4)[colnames(df_4) == "mg_cell_type_distinct"] = "CellType"
colnames(df_4)[colnames(df_4) == "gensini_bin"] = "Gensini_bin"

```

```{r}
set.seed(1994)
df_3 <- fread('../Study_3_2019/all_batches_processed_mg_10K.csv',
              nThread = 7) %>%
  as.data.frame() %>%
  dplyr::select(c(useMarkers,  "sample_id", "CellTypes", "Batch",
                  "Age", "Statin", "Gender", "Gensini_bin"))

colnames(df_3)[colnames(df_3) == "CellTypes"] = "CellType"
```

```{r}
df_all <- rbind(df_4, df_3)
```


```{r}
df_all[, useMarkers] <- cyCombine::transform_asinh(df_all, markers = useMarkers, derand = F)
```


```{r}
common_celltypes <- intersect(unique(df_3$CellType), unique(df_4$CellType))
```


```{r}
df_all <- df_all %>%
    dplyr::filter(CellType %in% final_celltypes)
raw_clusters <- runFuseSOM(df_all, markers = useMarkers, numClusters = 11)$clusters

aricode::ARI(raw_clusters, df_all$CellType)
```

```{r}
load('../sce_dat/study_4_MMD_VAE_updated.RData')
load('../sce_dat/study_3_MMD_VAE_updated.RData')
```

```{r}
df_4_norm <- assay(sce_norm, 'norm') %>%
  t() %>%
  as.data.frame() %>%
    dplyr::mutate(Celltype_new = sce_norm$Celltype_new) %>%
    dplyr::mutate(Celltype = sce_norm$mg_cell_type_distinct) %>%
    dplyr::mutate(batch = sce_norm$CyTOF.Batch) %>%
    dplyr::mutate(sample_id = sce_norm$sample_id) %>%
    dplyr::mutate(Age = sce_norm$Age) %>%
    dplyr::mutate(Gender = sce_norm$Gender) %>%
    dplyr::mutate(Statin = sce_norm$Statin) %>%
    dplyr::mutate(Gensini = as.factor(sce_norm$gensini_bin))

df_4_vae <- reducedDim(sce_norm, type = 'VAE') %>%
  as.data.frame() %>%
    dplyr::mutate(Celltype = sce_norm$mg_cell_type_distinct) %>%
    dplyr::filter(Celltype %in% final_celltypes)
```


```{r}
df_3_norm <- assay(sce_3_norm, 'norm') %>%
  t() %>%
  as.data.frame() %>%
    dplyr::mutate(Celltype_new = sce_3_norm$Celltype_new) %>%
    dplyr::mutate(Celltype = sce_3_norm$CellTypes) %>%
    dplyr::mutate(batch = sce_3_norm$Batch) %>%
    dplyr::mutate(sample_id = sce_3_norm$sample_id) %>%
    dplyr::mutate(Age = sce_3_norm$Age) %>%
    dplyr::mutate(Gender = sce_3_norm$Gender) %>%
    dplyr::mutate(Statin = sce_3_norm$Statin) %>%
    dplyr::mutate(Gensini = as.factor(sce_3_norm$Gensini_bin))

df_3_vae <- reducedDim(sce_3_norm, type = 'VAE') %>%
  as.data.frame() %>%
    dplyr::mutate(Celltype = sce_3_norm$CellTypes)  %>%
    dplyr::filter(Celltype %in% final_celltypes)
```

```{r}
df_all_norm <- rbind(df_4_norm, df_3_norm) %>%
    as.data.frame() %>%
    dplyr::filter(Celltype %in% final_celltypes)

colnames(df_all_norm) <- gsub("-", "_", colnames(df_all_norm))
```

```{r}
norm_clusters <- runFuseSOM(df_all_norm, markers = useMarkers,
                            numClusters = 11)$clusters

aricode::ARI(norm_clusters, df_all$CellType)
```

```{r}
assay(sce_3_norm, "raw", withDimnames = F) <- t(df_all %>% 
                                                    filter(Batch %like% "3") %>%
                                                    dplyr::select(useMarkers))
assay(sce_norm, "raw", withDimnames = F) <- t(df_all %>% filter(Batch %like% "4") %>%
                                                    dplyr::select(useMarkers))
```

# Save SCE objects
```{r, eval=F}
save(sce_norm, file = '../sce_dat/study_4_MMD_VAE_final.RData')
save(sce_3_norm, file = '../sce_dat/study_3_MMD_VAE_final.RData')
```
