root <- Node$new("Root")
  myeloid <- root$AddChild('Myeloid')
    `14+ monos` <- myeloid$AddChild('14+ monos')
    `16+ monos` <- myeloid$AddChild('16+ monos') 
  DCs <- root$AddChild('DCs')
    pDCs <- DCs$AddChild('pDCs')
    mDCs <- DCs$AddChild('mDCs')
      `CD141+ DCs` <- mDCs$AddChild('CD141+ DCs')
      `CD1c+ DCs` <- mDCs$AddChild('CD1c+ DCs')
  NK <- root$AddChild('NK')
  `B cells` <- root$AddChild('B cells')
  CD3 <- root$AddChild('CD3')
    CD8hi <- CD3$AddChild('CD8hi')
    CD8lo <- CD3$AddChild('CD8lo')
    CD4 <- CD3$AddChild('CD4')
      `CD4+ Tconv` <- CD4$AddChild('CD4+ Tconv')
      `CD4+ Treg` <- CD4$AddChild('CD4+ Treg')
  other <- root$AddChild('other')

      
plot(root)
plot(as.dendrogram(root), center = TRUE)

